// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ViewSettings.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ViewSettings
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: NanoSights/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for ViewSettings 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ViewSettings data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.NanoAnalytics`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ViewSettings: AutoGenerated.ZAutoGenViewSettings
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ViewSettings in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenViewSettings: Custom.Data.CustomItem
  {
    /// <summary>
    /// NanoAnalytics as bool. <br/>
    /// To get nullable use .Get("NanoAnalytics") as bool?;
    /// </summary>
    public bool NanoAnalytics => _item.Bool("NanoAnalytics");

    /// <summary>
    /// NanoCustom as bool. <br/>
    /// To get nullable use .Get("NanoCustom") as bool?;
    /// </summary>
    public bool NanoCustom => _item.Bool("NanoCustom");

    /// <summary>
    /// NanoInsights as bool. <br/>
    /// To get nullable use .Get("NanoInsights") as bool?;
    /// </summary>
    public bool NanoInsights => _item.Bool("NanoInsights");
  }
}